<?php

header('Content-Type: application/rss+xml; charset=utf-8');

//echo file_get_contents('https://www.upwork.com/ab/feed/jobs/rss?budget=0-99%2C100-499%2C500-999%2C1000-4999&client_hires=1-9%2C10-&contractor_tier=1%2C2&duration_v2=week%2Cmonth&q=php+mysql&sort=renew_time_int+desc&user_location_match=1&paging=0%3B10&api_params=1&securityToken=705f6dac6f40e7c3f3ded7212e4b328d93bb1cf4d5bca45c3e2704c0c1267d378b773b72d1d395cfba04d30e54db37ba70737f62426e45ded2f9e490b3a9a2d4&userUid=782395009780232192&orgUid=782395009780232194');

?><?xml version="1.0" encoding="UTF-8"?><rss xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0"><channel><title><![CDATA[All jobs | upwork.com]]></title><link><![CDATA[https://www.upwork.com/ab/feed/jobs/rss?api_params=1&amp;budget=0-99%2C100-499%2C500-999%2C1000-4999&amp;client_hires=1-9%2C10-&amp;contractor_tier=1%2C2&amp;duration_v2=week%2Cmonth&amp;orgUid=782395009780232194&amp;paging=0%3B10&amp;q=php%20mysql&amp;securityToken=705f6dac6f40e7c3f3ded7212e4b328d93bb1cf4d5bca45c3e2704c0c1267d378b773b72d1d395cfba04d30e54db37ba70737f62426e45ded2f9e490b3a9a2d4&amp;sort=renew_time_int%20desc&amp;userUid=782395009780232192&amp;user_location_match=1]]></link><description><![CDATA[All jobs as of December 08, 2018 03:41 UTC]]></description><language>en-us</language><pubDate>Sat, 08 Dec 2018 03:41:05 +0000</pubDate><copyright>© 2003-2018 Upwork Corporation</copyright><docs>http://blogs.law.harvard.edu/tech/rss</docs><generator>Upwork Corporation</generator><managingEditor>rss@upwork.com (Upwork Corporation)</managingEditor><image><url>https://www.upwork.com/images/rss_logo.png</url><title><![CDATA[All jobs | upwork.com]]></title><link><![CDATA[https://www.upwork.com/ab/feed/jobs/rss?api_params=1&amp;budget=0-99%2C100-499%2C500-999%2C1000-4999&amp;client_hires=1-9%2C10-&amp;contractor_tier=1%2C2&amp;duration_v2=week%2Cmonth&amp;orgUid=782395009780232194&amp;paging=0%3B10&amp;q=php%20mysql&amp;securityToken=705f6dac6f40e7c3f3ded7212e4b328d93bb1cf4d5bca45c3e2704c0c1267d378b773b72d1d395cfba04d30e54db37ba70737f62426e45ded2f9e490b3a9a2d4&amp;sort=renew_time_int%20desc&amp;userUid=782395009780232192&amp;user_location_match=1]]></link></image>
<item><title><![CDATA[Custom PHP MYSQL JQUERY ANGULAR / LAVARAVEL project - Upwork]]></title><link>https://www.upwork.com/jobs/Custom-PHP-MYSQL-JQUERY-ANGULAR-LAVARAVEL-project_%7E01794356e432f4d896?source=rss</link><description><![CDATA[I will need to meet personally and brief the project.<br />
Only candidates from Orlando FL <br /><br />
PHP MYSQL JQUERY ANGULAR / LAVARAVEL project<br /><br /><b>Budget</b>: $800
<br /><b>Posted On</b>: December 08, 2018 03:41 UTC<br /><b>Category</b>: Web, Mobile &amp; Software Dev &gt; Web Development
<br /><b>Skills</b>:        AngularJS,                     Laravel Framework,                     Node.js            <br /><b>Location Requirement</b>: Only freelancers located in the United States may apply.
<br /><b>Country</b>: United States<br /><a href="https://www.upwork.com/jobs/Custom-PHP-MYSQL-JQUERY-ANGULAR-LAVARAVEL-project_%7E01794356e432f4d896?source=rss">click to apply</a>]]></description><content:encoded><![CDATA[I will need to meet personally and brief the project.<br />
Only candidates from Orlando FL <br /><br />
PHP MYSQL JQUERY ANGULAR / LAVARAVEL project<br /><br /><b>Budget</b>: $800
<br /><b>Posted On</b>: December 08, 2018 03:41 UTC<br /><b>Category</b>: Web, Mobile &amp; Software Dev &gt; Web Development
<br /><b>Skills</b>:        AngularJS,                     Laravel Framework,                     Node.js            <br /><b>Location Requirement</b>: Only freelancers located in the United States may apply.
<br /><b>Country</b>: United States<br /><a href="https://www.upwork.com/jobs/Custom-PHP-MYSQL-JQUERY-ANGULAR-LAVARAVEL-project_%7E01794356e432f4d896?source=rss">click to apply</a>]]></content:encoded><pubDate>Tue, 13 Nov 2018 16:50:23 +0000</pubDate><guid>https://www.upwork.com/jobs/Custom-PHP-MYSQL-JQUERY-ANGULAR-LAVARAVEL-project_%7E01794356e432f4d896?source=rss</guid></item><item><title><![CDATA[Seeking Joomla developer for ongoing maintenance and feature expansion of custom component packages. - Upwork]]></title><link>https://www.upwork.com/jobs/Seeking-Joomla-developer-for-ongoing-maintenance-and-feature-expansion-custom-component-packages_%7E01c03e1caa3c7cb348?source=rss</link><description><![CDATA[We have developed and now support several private Joomla! modules, components, and plugins that we are seeking support for the ongoing maintenance and development.&nbsp;&nbsp;Our clients submit regular requests that we need to satisfy quickly.<br /><br />
We are seeking an experienced developer that can work with us over a long period of time, building an awareness of our existing codebase, helping us maintain the software and satisfy client feature requests to expand the product suite.<br /><br /><br /><b>Posted On</b>: December 08, 2018 03:41 UTC<br /><b>Category</b>: Web, Mobile &amp; Software Dev &gt; Web Development
<br /><b>Skills</b>:        Bootstrap,                     HTML,                     JavaScript,                     Joomla,                     jQuery,                     MySQL Programming,                     PHP,                     PSD to HTML,                     Web Design            <br /><b>Location Requirement</b>: Only freelancers located in the United States may apply.
<br /><b>Country</b>: United States<br /><a href="https://www.upwork.com/jobs/Seeking-Joomla-developer-for-ongoing-maintenance-and-feature-expansion-custom-component-packages_%7E01c03e1caa3c7cb348?source=rss">click to apply</a>]]></description><content:encoded><![CDATA[We have developed and now support several private Joomla! modules, components, and plugins that we are seeking support for the ongoing maintenance and development.&nbsp;&nbsp;Our clients submit regular requests that we need to satisfy quickly.<br /><br />
We are seeking an experienced developer that can work with us over a long period of time, building an awareness of our existing codebase, helping us maintain the software and satisfy client feature requests to expand the product suite.<br /><br /><br /><b>Posted On</b>: December 08, 2018 03:41 UTC<br /><b>Category</b>: Web, Mobile &amp; Software Dev &gt; Web Development
<br /><b>Skills</b>:        Bootstrap,                     HTML,                     JavaScript,                     Joomla,                     jQuery,                     MySQL Programming,                     PHP,                     PSD to HTML,                     Web Design            <br /><b>Location Requirement</b>: Only freelancers located in the United States may apply.
<br /><b>Country</b>: United States<br /><a href="https://www.upwork.com/jobs/Seeking-Joomla-developer-for-ongoing-maintenance-and-feature-expansion-custom-component-packages_%7E01c03e1caa3c7cb348?source=rss">click to apply</a>]]></content:encoded><pubDate>Tue, 13 Nov 2018 04:21:26 +0000</pubDate><guid>https://www.upwork.com/jobs/Seeking-Joomla-developer-for-ongoing-maintenance-and-feature-expansion-custom-component-packages_%7E01c03e1caa3c7cb348?source=rss</guid></item></channel></rss>
