<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="/favicon.ico">

  <title>Open Revenue Data - CJTrowbridge.com</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-12">
      <p><a href="/">&lt;&lt; Back To Home Page</a></p>
      
      <h1>Open Revenue Data</h1>
      <p>Per the example of Pieter Levels, I have decided to create a dashboard for my projects this year in order to track and share my results as I communicate about them on my blog.</p>
      
      <div class="card">
        <div class="card-body">
          <h2>Revenue Mix</h2>
          <p>A major goal for me this year is diversification of my revenue sources. They say that the average millionaire has seven sources of income. Too many wantrepreneurs today are spending a huge amount of time and effort on a single project. Any failure or challenges in that project have an outsized impact on the livelihood and security of the entrepreneur. If the goal is to build a lifestyle business, it doesn't make sense to spend so much time on any one thing. Thus entrepreneurial diversification is a no brainer.</p>
          <p>I want to have at least three significant sources of income by the end of the year. Each one should produce at least 20% of my total revenue. This means problems in one project can not have an outsized impact on my livelihood.</p>
          <p class="text-center">
            <iframe width="800" height="304.5" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQWKMX0Yxi29TBATsQTDqcaPClYdnswQEExZwBO712WKwb9Ajnlq0DJsEcQUwxJNsgDORft9zw2gkqT/pubchart?oid=628337542&amp;format=interactive"></iframe>
          </p>
        </div>
      </div>
      
      <br>
      
      <div class="card">
        <div class="card-body">
          <h2>Revenue Totals</h2>
          <p>Here is where I track the total amounts generated by each project. The difference here is that I am showing the top lines, not the mix. Most entrepreneurial thought leaders advise starting with a number for how much profit you need to live. I am currently a student who does not need to have any income. Thus, I am less focused on the total than on coming up with a steady nonzero amount for each project's revenue.</p>
          <p class="text-center">
            <iframe width="800" height="303.5" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQWKMX0Yxi29TBATsQTDqcaPClYdnswQEExZwBO712WKwb9Ajnlq0DJsEcQUwxJNsgDORft9zw2gkqT/pubchart?oid=1236350701&amp;format=interactive"></iframe>
          </p>
        </div>
      </div>
          
    </div>
  </div>
</div>


  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>
